version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ARX_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ARX_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - arxiveprior-sqldata:/var/opt/mssql

  arx.extract.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Storage__StorageConnectionString=${ARX_AZURE_EXTRACT_STORAGE_CS}
      - PATH_BASE=/extract-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5001:80"
      - "9101:81"
      - "6001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  arx.Extract.BackgroundTasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development      
      - Storage__StorageConnectionString=${ARX_AZURE_EXTRACT_STORAGE_CS}
      - EventBusConnection=${ARX_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ARX_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ARX_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False

  journal.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__grpcExtract=http://arx.extract.api:81
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ARX_AZURE_JOURNAL_DB:-Server=sqldata;Database=arxiveprior.Services.JournalDb;User Id=sa;Password=Pass@word}      
      - PATH_BASE=/journal-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5002:80"
      - "9102:81"
      - "6002:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  journal.backgroundtasks:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - ConnectionString=${ARX_AZURE_JOURNAL_DB:-Server=sqldata;Database=arxiveprior.Services.JournalDb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${ARX_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ARX_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ARX_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - urls__grpcExtract=http://arx.extract.api:81
  
  journal.infrastructure:
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionString=${ARX_AZURE_JOURNAL_DB:-Server=sqldata;Database=arxiveprior.Services.JournalDb;User Id=sa;Password=Pass@word}     

volumes:

  arxiveprior-sqldata: