version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.8-management-alpine

  arx.extract.api:
    image: ${DOCKER_REGISTRY-}arxextractapi
    build:
      context: .
      dockerfile: Services/Extract/arx.Extract.API/Dockerfile

  arx.Extract.BackgroundTasks:
    image: ${DOCKER_REGISTRY-}arxextractbackgroundtasks
    build:
      context: .
      dockerfile: Services/Extract/arx.Extract.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  journal.api:
    image: ${DOCKER_REGISTRY-}journalapi
    build:
      context: .
      dockerfile: Services/Journal/Journal.API/Dockerfile    

  journal.backgroundtasks:
    image: ${DOCKER_REGISTRY-}journalbackgroundtasks
    build:
      context: .
      dockerfile: Services/Journal/Journal.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq 

  journal.infrastructure:
    image: ${DOCKER_REGISTRY-}journalinfrastructure
    build:
      context: .
      dockerfile: Services/Journal/Journal.Infrastructure/Dockerfile

