version: '3.4'

services:
 rabbitmq:
    image: rabbitmq:3.8.7

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest  

  arx.extract.api:
    image: ${DOCKER_REGISTRY-}arxextractapi
    build:
      context: .
      dockerfile: Services/Extract/arx.Extract.API/Dockerfile

  arx.Extract.BackgroundTasks:
    image: ${DOCKER_REGISTRY-}arxextractbackgroundtasks
    build:
      context: .
      dockerfile: Services/Extract/arx.Extract.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  journal.api:
    image: ${DOCKER_REGISTRY-}journalapi
    build:
      context: .
      dockerfile: Services/Journal/Journal.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  journal.backgroundtasks:
    image: ${DOCKER_REGISTRY-}journalbackgroundtasks
    build:
      context: .
      dockerfile: Services/Journal/Journal.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq
      - sqldata 

  journal.infrastructure:
    image: ${DOCKER_REGISTRY-}journalinfrastructure
    build:
      context: .
      dockerfile: Services/Journal/Journal.Infrastructure/Dockerfile
    depends_on:      
      - sqldata 