version: '3.4'

services:
  arx.extract.api:
    image: ${DOCKER_REGISTRY-}arxextractapi
    build:
      context: .
      dockerfile: arx.Extract.API/Dockerfile

  arx.Extract.BackgroundTasks:
    image: ${DOCKER_REGISTRY-}arxextractbackgroundtasks
    build:
     context: .
     dockerfile: arx.Extract.BackgroundTasks/Dockerfile