version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  arx.extract.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  arx.Extract.BackgroundTasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__StorageConnectionString=${ARX_AZURE_EXTRACT_STORAGE_CS}
      - Settings__SubjectTableName=Subjects